### ISSUE TITLE
无法自动刮削内容

### ISSUE THREAD

**Issue by helloxz** [Libitum/jellyfin-plugin-douban#15]
媒体库设置如下，无法自动刮削内容：
![image](https://user-images.githubusercontent.com/7276531/77758354-c1990a80-706d-11ea-84e8-9be72d95bb61.png)
![image](https://user-images.githubusercontent.com/7276531/77758368-cb227280-706d-11ea-9a9a-d3e0735b9b43.png)
但是我单独识别mo某部影片，输入豆瓣的ID可以刮削，如下图。
![image](https://user-images.githubusercontent.com/7276531/77758418-e4c3ba00-706d-11ea-9c03-f19cfd21494e.png)

请问下大佬是不是我哪里设置不对呀？

**Comment by Libitum** [comment]
请问有试过 “刷新媒体库” 么？如果媒体库之前已经通过其他刮削器更新过 meta 的话，默认不会自动重新刷新的

**Comment by helloxz** [comment]
我尝试新建了一个库，然后放了几部新电影进去，对这个库单独刷新也不行。
* 操作系统：Debian 10
* jellyfin版本：10.5

**Comment by Libitum** [comment]
这个就有点奇怪了...我也是 Debian 10，你介意把日志打开然后日志发我一下么？
在 config/log 下面把你当天的 log 发我一下。
或者如果你熟悉 linux 操作的话，可以把 grep -i douban ${今天日期}.log 的结果发我看一下？

**Comment by helloxz** [comment]
好的，等我回去复现问题并收集日志后再发你。

**Comment by helloxz** [comment]
> 这个就有点奇怪了...我也是 Debian 10，你介意把日志打开然后日志发我一下么？
> 在 config/log 下面把你当天的 log 发我一下。
> 或者如果你熟悉 linux 操作的话，可以把 grep -i douban ${今天日期}.log 的结果发我看一下？

请问下您使用的jellyfin版本是多少呢？我和另一个小伙伴遇到了同样的问题，都是`10.5.0`

**Comment by helloxz** [comment]
这是从日志中看到的:
```
[2020-04-04 13:57:57.577 +08:00] [ERR] Error in "Douban Movie Provider"
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Jellyfin.Plugin.Douban.BaseProvider.SearchSidByName(String name, CancellationToken cancellationToken) in /Users/wangfenglei/Workspace/jellyfin/jellyfin-plugin-douban/Jellyfin.Plugin.Douban/BaseProvider.cs:line 78
   at Jellyfin.Plugin.Douban.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken) in /Users/wangfenglei/Workspace/jellyfin/jellyfin-plugin-douban/Jellyfin.Plugin.Douban/MovieProvider.cs:line 53
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by Libitum** [comment]
Hi 请问您是所有电影都无法刮削么？还是部分不可以？这个错误应该是请求频繁被豆瓣临时封了 ip，不过应该也是临时性的。我之前遇到的 case 是第二天就解禁了。
我今天再尝试复现一下这个问题

**Comment by helloxz** [comment]
我觉得应该不是被豆瓣封了IP，我和另一个小伙伴也有同样的情况，所有电影无法自动刮削。但如果我通过识别 - 手动输入豆瓣ID是可以搜索到的。

**Comment by Libitum** [comment]
好的，我今天测试一下，多谢反馈哈

**Comment by helloxz** [comment]
好的，辛苦大佬，有需要我这边提供什么请告知。

**Comment by Libitum** [comment]
Hi @helloxz 初步怀疑是 jellyfin 10.5 的兼容性问题。10.5 已经换成 netstandard2.1 了。我把插件也更新了一下，自己测试没问题，能麻烦你帮忙测试一下么？谢谢！
[pre-release 0.4.0](https://github.com/Libitum/jellyfin-plugin-douban/releases/tag/v0.4.0)

**Comment by helloxz** [comment]
谢谢大佬，我回去后更新一波再给您反馈。

**Comment by siryle1213** [comment]
大佬，有个小小的建议：就是电视剧，如果标题没有s01的话，能不能默认让他归为第一季

**Comment by helloxz** [comment]
大佬，我这边更新了插件，并重启jellyfin，结果还是不行，是我姿势不对吗？日志如下：
```
[2020-04-17 21:56:54.411 +08:00] [INF] Douban:GetMetadata movie name: Yip_Man_4_The_Finale.2019.WEB-DL.4k.H265.CN.AAC-PTHome
[2020-04-17 21:56:54.417 +08:00] [INF] Douban: Trying to search sid by name: "Yip_Man_4_The_Finale.2019.WEB-DL.4k.H265.CN.AAC-PTHome"
[2020-04-17 21:56:54.863 +08:00] [ERR] Error in "Douban Movie Provider"
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Jellyfin.Plugin.Douban.BaseProvider.SearchSidByName(String name, CancellationToken cancellationToken) in C:\Users\Ferry\Source\jellyfin-plugin-douban\Jellyfin.Plugin.Douban\BaseProvider.cs:line 78
   at Jellyfin.Plugin.Douban.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken) in C:\Users\Ferry\Source\jellyfin-plugin-douban\Jellyfin.Plugin.Douban\MovieProvider.cs:line 53
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Comment by Libitum** [comment]
这么尴尬么.... 你是 debian9 对吧？我弄个虚拟机试一下

**Comment by Libitum** [comment]
@helloxz  您好，可以尝试一下 0.6 版本，加了一些爬虫策略，来避免被 Douban 封禁。
