### ISSUE TITLE
插件不支持10.6.0版本，作者大大有空更新下哦

### ISSUE THREAD

**Issue by ssyangchn** [Libitum/jellyfin-plugin-douban#22]
插件不支持10.6.0版本，作者大大有空更新下哦

**Comment by yanwen** [comment]
10.6.1版本同样出现 不能用的情况。

大佬有空的话 方便更新一下不？？感谢。 @Libitum

**Comment by Libitum** [comment]
@ssyangchn @yanwen  
10.6.0 abi 更新了，我这两天在看。顺便 10.6.0 可以支持直接添加插件啦，这个功能我也在适配哈，请大家稍等

**Comment by Libitum** [comment]
@ssyangchn @yanwen 最新版本已支持 10.6.0，请更新试一下，谢谢！
顺便，也已支持使用 Repository 来直接安装插件 :-)

**Comment by ssyangchn** [comment]
> @ssyangchn @yanwen 最新版本已支持 10.6.0，请更新试一下，谢谢！
> 顺便，也已支持使用 Repository 来直接安装插件 :-)

用仓库安装失败了
```
[13:31:08] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json
System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。
 ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifest, CancellationToken cancellationToken)

**Comment by yanwen** [comment]
> > @ssyangchn @yanwen 最新版本已支持 10.6.0，请更新试一下，谢谢！
> > 顺便，也已支持使用 Repository 来直接安装插件 :-)
> 
> 用仓库安装失败了
> 
> ```
> [13:31:08] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json
> System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。
>  ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
>    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
>    at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifest, CancellationToken cancellationToken)
> ```

可能是网络不好。要不你下载之后再安装吧。

**Comment by ssyangchn** [comment]
> > > @ssyangchn @yanwen 最新版本已支持 10.6.0，请更新试一下，谢谢！
> > > 顺便，也已支持使用 Repository 来直接安装插件 :-)
> > 
> > 
> > 用仓库安装失败了
> > ```
> > [13:31:08] [ERR] [11] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json
> > System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。
> >  ---> System.Net.Sockets.SocketException (11004): 请求的名称有效，但是找不到请求的类型的数据。
> >    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
> >    --- End of inner exception stack trace ---
> >    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
> >    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
> >    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> >    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> >    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
> >    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> >    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> >    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
> >    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
> >    at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
> >    at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifest, CancellationToken cancellationToken)
> > ```
> 
> 可能是网络不好。要不你下载之后再安装吧。

确实是我网络问题，换个dns之后能下载成功了
