### ISSUE TITLE
jellyfin  10.6.2 按照一直失败

### ISSUE THREAD

**Issue by buggogogo** [Libitum/jellyfin-plugin-douban#26]
群晖：6.2
docker:18
jellyfin:10.6.2
问题描述：使用plugins下直接放文件的方式，重启后不显示已安装插件，使用reponsitory的方式，在元数据区不显示豆瓣可安装插件，（fq问题已解决，在容器中可以正常ping google）还是出现下面的问题，希望牛人帮看看，倒腾了大半天都不行。
错误信息：[2020-08-09 17:36:09.535 +00:00] [ERR] [6] Emby.Server.Implementations.Updates.InstallationManager: An error occurred while accessing the plugin manifest: "https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json"
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.Updates.InstallationManager.GetPackages(String manifest, CancellationToken cancellationToken)

**Comment by Libitum** [comment]
@buggogogo 从错误提示看，还是因为无法访问 https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json。 可以尝试以下浏览器直接访问是否正常？

或者，也可以试一下用这个 url：https://cdn.jsdelivr.net/gh/libitum/jellyfin-plugin-douban/manifest.json
这是个 cdn 加速的 url，不受访问约束。

**Comment by Libitum** [comment]
> 使用plugins下直接放文件的方式，重启后不显示已安装插件

关于这一点 理论上是不会的，想确认一下是不是解压后的 dll 文件放在了 plugins 目录下?

**Comment by buggogogo** [comment]
> @buggogogo 从错误提示看，还是因为无法访问 [https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json。](https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json%E3%80%82) 可以尝试以下浏览器直接访问是否正常？
> 
> 或者，也可以试一下用这个 url：https://cdn.jsdelivr.net/gh/libitum/jellyfin-plugin-douban/manifest.json
> 这是个 cdn 加速的 url，不受访问约束。

一会我试试

**Comment by buggogogo** [comment]
> > 使用plugins下直接放文件的方式，重启后不显示已安装插件
> 
> 关于这一点 理论上是不会的，想确认一下是不是解压后的 dll 文件放在了 plugins 目录下?
解压后吧dll放到plugins下面

**Comment by buggogogo** [comment]
谢谢各位，使用离线安装的方式已经成功，时自己映射目录有问题，按照文档说明操作是没有任何问题的
