### ISSUE TITLE
jellyfin10.7安装2.0无法显示

### ISSUE THREAD

**Issue by gldl137** [Libitum/jellyfin-plugin-douban#38]
群晖Docker 10.7安装douban2.0，元数据无法找到。
![QQ拼音截图20210220195543](https://user-images.githubusercontent.com/54521752/108594786-f107e280-73b6-11eb-876a-4072f873536e.png)
![QQ拼音截图20210220195553](https://user-images.githubusercontent.com/54521752/108594788-f2390f80-73b6-11eb-85e2-9223c8959bf4.png)
![QQ拼音截图20210220195617](https://user-images.githubusercontent.com/54521752/108594789-f36a3c80-73b6-11eb-82d5-2f10b03db557.png)
![QQ拼音截图20210220195639](https://user-images.githubusercontent.com/54521752/108594790-f49b6980-73b6-11eb-909e-696322937025.png)

**Comment by Libitum** [comment]
@gldl137 请问您是通过以下哪种方式安装的呢？
1. 如果是通过 repo 安装的，之前 repo 里的 版本号有个 bug，已经 fix。麻烦重新安装试一下。
2. 如果是下载 zip 拷贝到 plugin 目录安装的，可能需要提供一下相关错误日志。

另外，不论通过哪种方式安装，都需要重启一下 Jellyfin 服务来生效哈

**Comment by zxerqw** [comment]
我好像遇到了相同的错误,日志如下

> [2021-02-23 12:40:07.409 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Douban, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Douban/Jellyfin.Plugin.Douban.dll"
[2021-02-23 12:40:07.413 +00:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error getting exported types from "Jellyfin.Plugin.Douban, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null"
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()

**Comment by gldl137** [comment]
[2021-02-23 13:30:09.718 +00:00] [INF] [1] Main: Jellyfin version: "10.7.0"
[2021-02-23 13:30:09.733 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_LOG_DIR, /config/log]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_CONFIG_DIR, /config/config]"]
[2021-02-23 13:30:09.736 +00:00] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[2021-02-23 13:30:09.736 +00:00] [INF] [1] Main: Operating system: "Linux"
[2021-02-23 13:30:09.736 +00:00] [INF] [1] Main: Architecture: X64
[2021-02-23 13:30:09.737 +00:00] [INF] [1] Main: 64-Bit Process: True
[2021-02-23 13:30:09.737 +00:00] [INF] [1] Main: User Interactive: True
[2021-02-23 13:30:09.737 +00:00] [INF] [1] Main: Processor count: 4
[2021-02-23 13:30:09.737 +00:00] [INF] [1] Main: Program data path: "/config"
[2021-02-23 13:30:09.737 +00:00] [INF] [1] Main: Web resources path: "/jellyfin/jellyfin-web"
[2021-02-23 13:30:09.737 +00:00] [INF] [1] Main: Application directory: "/jellyfin/"
[2021-02-23 13:30:09.854 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/config/cache"
[2021-02-23 13:30:09.884 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-02-23 13:30:09.884 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2021-02-23 13:30:09.885 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-02-23 13:30:09.889 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2021-02-23 13:30:09.889 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2021-02-23 13:30:09.911 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error deserializing "﻿{
  \"category\": \"\",
  \"changelog\": \"\",
  \"description\": \"\",
  \"guid\": \"f9d3f058-41e2-ac08-b819-777c28fd63a9\",
  \"name\": \"Kodi Sync Queue\",
  \"overview\": \"\",
  \"owner\": \"\",
  \"targetAbi\": \"10.7.0.0\",
  \"timestamp\": \"0001-01-01T00:00:00.0000000Z\",
  \"version\": \"6.2012.600.2703\",
  \"status\": \"Malfunctioned\",
  \"autoUpdate\": false
}".
System.Text.Json.JsonException: '0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadManifest(String dir)
[2021-02-23 13:30:09.914 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error deserializing "﻿{
  \"category\": \"\",
  \"changelog\": \"\",
  \"description\": \"\",
  \"guid\": \"e325b8d5-5f54-447f-a38a-a951b933d22c\",
  \"name\": \"Douban\",
  \"overview\": \"\",
  \"owner\": \"\",
  \"targetAbi\": \"10.7.0.0\",
  \"timestamp\": \"0001-01-01T00:00:00.0000000Z\",
  \"version\": \"2.0.0.0\",
  \"status\": \"Malfunctioned\",
  \"autoUpdate\": false
}".
System.Text.Json.JsonException: '0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Emby.Server.Implementations.Plugins.PluginManager.LoadManifest(String dir)

**Comment by zxerqw** [comment]
> 我好像遇到了相同的错误,日志如下
> 
> > [2021-02-23 12:40:07.409 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "Jellyfin.Plugin.Douban, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/Douban/Jellyfin.Plugin.Douban.dll"
> > [2021-02-23 12:40:07.413 +00:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error getting exported types from "Jellyfin.Plugin.Douban, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null"
> > System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> > File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> > at System.Reflection.RuntimeAssembly.GetExportedTypes()
> > at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()

忘记回复，我的已经正常了，是jellyfin版本错误，没更新镜像。

**Comment by gldl137** [comment]
> 。

你是用的什么版本

**Comment by zxerqw** [comment]
> > 。
> 
> 你是用的什么版本

10.7.0 RC3

**Comment by gldl137** [comment]
> > > 。
> > 
> > 
> > 你是用的什么版本
> 
> 10.7.0 RC3

我是群晖Docker安装，应该是这个原因

**Comment by gldl137** [comment]
我的jellyfin版本问题

**Comment by Libitum** [comment]
嗯是的 docker 的镜像也需要更新到 10.7.0。多谢楼上各位！

**Comment by wolonggl** [comment]
每日编译jellyfin版本安装豆瓣插件也存在一样的问题，提示有故障。。。
