### ISSUE TITLE
安装2.0rc1版本插件出错

### ISSUE THREAD

**Issue by dayatang** [Libitum/jellyfin-plugin-douban#39]
<img width="840" alt="截屏2021-02-22 下午10 29 49" src="https://user-images.githubusercontent.com/4167667/108721996-99f04200-755d-11eb-88da-391caf65c823.png">
查看后台日志，报错内容如下：

> [14:26:19] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.0.105:8096/Packages/Installed/Douban?AssemblyGuid=e325b8d5-5f54-447f-a38a-a951b933d22c&version=2.0.0-rc1
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Version.Parse(String input)
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)

上面的问题请看一下。感谢作者，辛苦了。

**Comment by Libitum** [comment]
@dayatang 查了一下是版本号的格式问题，已经 fix。请重试一下，谢谢！

**Comment by Eadger** [comment]
我这里还是无限转圈圈
![image](https://user-images.githubusercontent.com/45703375/108804324-1122e600-75f1-11eb-943d-784fbbd58b8b.png)
重启整个docker都不行

**Comment by Libitum** [comment]
@Eadger 这就有点神奇了...难道是访问 github 的文件访问不到？请问能否提供一下相关日志呢？谢谢！

**Comment by Eadger** [comment]
> @Eadger 这就有点神奇了...难道是访问 github 的文件访问不到？请问能否提供一下相关日志呢？谢谢！

[2021-02-24 09:54:12.980 +00:00] [WRN] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "172.17.0.1". Time (slow): 0:00:02.6402095. "http://192.168.1.107:8096/Packages/Douban?AssemblyGuid=e325b8d5-5f54-447f-a38a-a951b933d22c"
[2021-02-24 10:01:57.228 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:02:09.229 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:03:09.230 +00:00] [INF] [28] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:04:09.232 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:05:09.235 +00:00] [INF] [23] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:06:09.236 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:07:09.238 +00:00] [INF] [10] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:08:09.242 +00:00] [INF] [11] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:09:09.244 +00:00] [INF] [10] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:10:09.246 +00:00] [INF] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:11:09.248 +00:00] [INF] [11] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2021-02-24 10:11:21.249 +00:00] [INF] [4] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2021-02-24 10:43:36.521 +00:00] [WRN] [10] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:172.17.0.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2021-02-24 10:43:36.530 +00:00] [INF] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:172.17.0.1" closed
[2021-02-24 11:17:12.501 +00:00] [INF] [43] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:172.17.0.1" request

**Comment by daoshuailx** [comment]
我jellyfin 10.6.4也遇到这个问题，尝试按照以前的方法手动安装，也不行，请问有办法手动安装吗

**Comment by cxfksword** [comment]
应该是最新的 2.0 编译依赖了 .net core 5版本，  但docker 没包含导致

```
stdout: [06:31:08] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.Douban, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Douban/Jellyfin.Plugin.Douban.dll
stdout: [06:31:08] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error getting exported types from Jellyfin.Plugin.Douban, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
stdout: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
stdout: 
stdout: File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
stdout:    at System.Reflection.RuntimeAssembly.GetExportedTypes()
stdout:    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
stdout: 
```

能编译.net5 和.net3 版本吗？

**Comment by xht592** [comment]
2.0版本安装提示找不到资源，1.0则无此问题
[2021-02-25 00:00:06.611 +08:00] [ERR] Error processing request. URL: "http://192.168.2.10:8096/Packages/Installed/Douban?AssemblyGuid=e325b8d5-5f54-447f-a38a-a951b933d22c&version=2.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Douban
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by dayatang** [comment]
尝试了安装2.0版仍然失败。下面是日志：

> [08:33:20] [INF] [10] Jellyfin.Plugin.Douban.MovieProvider: Douban: Trying to get douban subject by sid: 24750968
[08:33:20] [ERR] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Error in Douban Movie Provider
MediaBrowser.Model.Net.HttpException: Bad Request
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
   at Jellyfin.Plugin.Douban.DoubanAccessor.GetResponse(String url, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Douban.BaseProvider.GetDoubanSubject(String sid, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Douban.BaseProvider.GetMetaFromDouban[T](String sid, String type, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Douban.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
[08:33:31] [WRN] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 172.18.0.1. Time (slow): 0:00:15.6480038. http://192.168.0.105:8096/Packages?PackageType=UserInstalled
[08:33:44] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.0.105:8096/Packages/Installed/Douban?AssemblyGuid=e325b8d5-5f54-447f-a38a-a951b933d22c&version=2.0.0.0
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Douban
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by Nokia-1208** [comment]
jellyfin 10.6.4也安装不了，手动也不行

**Comment by Libitum** [comment]
> 应该是最新的 2.0 编译依赖了 .net core 5版本， 但docker 没包含导致
> stdout: [06:31:08] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly Jellyfin.Plugin.Douban, 
> 能编译.net5 和.net3 版本吗？

@cxfksword 请问您是手动安装的 jellyfin 么？是否考虑使用 docker？官方 docker 的 10.7.0rc3 的版本默认已经是 net5. 10.7.0 未来应该也支持 net5 了

**Comment by Libitum** [comment]
@daoshuailx @Nokia-1208 抱歉由于 Jellyfin 官方 10.6 和 10.7 的 api 差别很大，比较难以同时维护。因此新的 2.0.0-rc1 只支持 Jellyfin 10.7.0-rc3 及未来的正式版。建议升级

**Comment by Libitum** [comment]
> 
> 
> 2.0版本安装提示找不到资源，1.0则无此问题
> [2021-02-25 00:00:06.611 +08:00] [ERR] Error processing request. URL: "http://192.168.2.10:8096/Packages/Installed/Douban?AssemblyGuid=e325b8d5-5f54-447f-a38a-a951b933d22c&version=2.0.0.0"
> MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Douban
> at MediaBrowser.Api.PackageService.Post(InstallPackage request)
> at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
> at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
> at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

您好，原因应该是因为 docker 镜像版本偏低，可以使用官方 Jellyfin 10.7.0rc3 的镜像试一下。

**Comment by Libitum** [comment]
> 
> 
> 尝试了安装2.0版仍然失败。下面是日志：
> 
> > [08:33:20] [INF] [10] Jellyfin.Plugin.Douban.MovieProvider: Douban: Trying to get douban subject by sid: 24750968
> > [08:33:20] [ERR] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Error in Douban Movie Provider
> > MediaBrowser.Model.Net.HttpException: Bad Request
> > at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options)
> > at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod)
> > at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod)
> > at Jellyfin.Plugin.Douban.DoubanAccessor.GetResponse(String url, CancellationToken cancellationToken)
> > at Jellyfin.Plugin.Douban.BaseProvider.GetDoubanSubject(String sid, CancellationToken cancellationToken)
> > at Jellyfin.Plugin.Douban.BaseProvider.GetMetaFromDouban[T](String sid, String type, CancellationToken cancellationToken)
> > at Jellyfin.Plugin.Douban.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
> > at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
> > [08:33:31] [WRN] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 172.18.0.1. Time (slow): 0:00:15.6480038. http://192.168.0.105:8096/Packages?PackageType=UserInstalled
> > [08:33:44] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.0.105:8096/Packages/Installed/Douban?AssemblyGuid=e325b8d5-5f54-447f-a38a-a951b933d22c&version=2.0.0.0
> > MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Douban
> > at MediaBrowser.Api.PackageService.Post(InstallPackage request)
> > at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
> > at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
> > at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

这个错误不是安装失败，是在抓取数据的时候被豆瓣临时 block 了。过段时间后重试应该就可以。这个问题后续会持续想办法优化

**Comment by Eadger** [comment]
> > @Eadger 这就有点神奇了...难道是访问 github 的文件访问不到？请问能否提供一下相关日志呢？谢谢！
> 
> [2021-02-24 09:54:12.980 +00:00] [WRN] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "172.17.0.1". Time (slow): 0:00:02.6402095. "http://192.168.1.107:8096/Packages/Douban?AssemblyGuid=e325b8d5-5f54-447f-a38a-a951b933d22c"
> [2021-02-24 10:01:57.228 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:02:09.229 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:03:09.230 +00:00] [INF] [28] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:04:09.232 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:05:09.235 +00:00] [INF] [23] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:06:09.236 +00:00] [INF] [44] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:07:09.238 +00:00] [INF] [10] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:08:09.242 +00:00] [INF] [11] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:09:09.244 +00:00] [INF] [10] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:10:09.246 +00:00] [INF] [25] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:11:09.248 +00:00] [INF] [11] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2021-02-24 10:11:21.249 +00:00] [INF] [4] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
> [2021-02-24 10:43:36.521 +00:00] [WRN] [10] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "::ffff:172.17.0.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
> [2021-02-24 10:43:36.530 +00:00] [INF] [10] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:172.17.0.1" closed
> [2021-02-24 11:17:12.501 +00:00] [INF] [43] Emby.Server.Implementations.HttpServer.HttpListenerHost: WS "::ffff:172.17.0.1" request

Jellyfin版本更新到 10.7.5 后，问题解决
