### ISSUE TITLE
适配版本：10.8.0

### ISSUE THREAD

**Issue by tossp** [Libitum/jellyfin-plugin-douban#52]
版本：10.8.0

操作系统：Linux

架构：X64

```
jellyfin    | [23:49:30] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Douban.ImageProvider
jellyfin    | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin    |    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParameters()
jellyfin    |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
jellyfin    | [23:49:30] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Douban.MovieProvider
jellyfin    | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin    |    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParameters()
jellyfin    |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
jellyfin    | [23:49:30] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.Douban.TVProvider
jellyfin    | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin    |    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParameters()
jellyfin    |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by li77leprince** [comment]
我的报错问题跟你一样，用的也是10.8.0。

**Comment by xiaod-dev** [comment]
10.8.0 同样的问题。现在有解么

**Comment by Alonglang** [comment]
同问题。。
[2022-06-29 15:10:57.075 +00:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Douban.ImageProvider"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2022-06-29 15:10:57.123 +00:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Douban.MovieProvider"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2022-06-29 15:10:57.124 +00:00] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating "Jellyfin.Plugin.Douban.TVProvider"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
